### ISSUE TITLE
Allow setting destination `agents` when no source exists

### ISSUE THREAD

**Issue by drewmullen** [hashicorp-services/tfm#126]
Often users do not have agents configured for TFE. Would be good to have the ability to map agents on the destination side without requiring input from the source. 

For example, if my config file looks like:

```hcl
workspaces = [
  "app1-dev",
  "app1-stg",
  "app1-prd",
]

destination_agentpool_assignments = "aws_eks_agent_pool"
# OR use an id
# destination_agentpool_id_assignments = "apool-123124"
```

**Comment by jeffmccollum** [comment]
We are going to release this in the version 0.5.0 that should be coming later today 🤞 
That said, it is only going to support setting an agent pool id, however we are going to revisit this in the 0.6.0 release later this month. There will be a new issue created later today I'll link to this one.
