### ISSUE TITLE
Do not error if `-last x` is used and tfe has < x states

### ISSUE THREAD

**Issue by drewmullen** [hashicorp-services/tfm#151]
If you pass `-last 5` when copying statefiles if TFE doesnt have that many statefiles, tfm errors out. This should be a warning to stdout instead of an error. For large migrations these jobs are run in automation and the error is not really useful

**Comment by mattmusich** [comment]
Hey Drew, we miss-read the output of the error we were getting and we can close this issue.

The failure was unrelated to last X > Y States, but that the last X command prompts for a y/n when running and we weren't aware of that expected input, which we solved for and we no longer have issues.

If anything a -y flag for last X to auto accept the prompt would be a nice to have but a simple works for us right now 
 `echo 'y' | tfm copy ...`

**Comment by jeffmccollum** [comment]
Using the `--autoapprove` flag will skip the prompt for the last command and should skip every other confirmation we have.
