### ISSUE TITLE
tfm ability to lock a workspace in TFE before performing the migration

### ISSUE THREAD

**Issue by drewmullen** [hashicorp-services/tfm#155]
It is best practice to lock a workspace prior to performing an actual migration. a flag to lock source workspaces prior to `copy` would be wonderful

**Comment by jeffmccollum** [comment]
Hey Drew!
I can see a couple ways of doing this feature.
1. At some point before copying the source workspaces or copying the states of source workspaces, preemptively lock the source workspaces. With this approach the source workspaces would be locked until the workspaces are unlocked again with another command / flag for unlocking.
2. When doing a `copy workspaces --state`, lock the source workspace, and after copying all the states in that workspace, unlock the source.

**Comment by Josh-Tracy** [comment]
What is the problem you are attempting to solve with this feature? We lock the destination workspace during state migration as it is a technical requirement to upload a state file. We then unlock it. Is the goal of locking the source workspace after migration to prevent continued usage of it after migration in instances where developers continue to try and use the source workspace after migration?

**Comment by drewmullen** [comment]
Hi All! Sorry should have included more about the use case in the description!

So the use case is to prevent usage of the source workspace once the migration has completed

**Comment by jeffmccollum** [comment]
@drewmullen We talked it through and we are going to put this in for version 0.6.0 this month. 

Here is what we are thinking of doing for the implementation. Create two new flags, `copy workspaces --lock` and `copy workspaces --unlock` This will look at all workspaces configured on the source side, via list, map, all, etc, and either lock them or unlock them based on the flag. This way the locks can be performed at any stage of the migration, like pre-state or after state migration, etc. 

Does that still align with what you are wanting? I think it's a great idea / feature, want to make sure it will work for you.

**Comment by drewmullen** [comment]
Yes! The only comment I forgot to request is that the settings are idempotent. So if a WS already is locked, don't error
