### ISSUE TITLE
Trying to Unmarshal an object of type "data-retention-policy-delete-olders", but "data-retention-policies" does not match

### ISSUE THREAD

**Issue by gaelik** [hashicorp-services/tfm#210]
**Describe the bug**
When using tfm 0.9.1 against TFE 202401-2, the following error message appears when doing a `tfm list workspaces`. 
The configuration was functional before the upgrade (ie when using 202312).

**To Reproduce**

```
$ ./tfm list workspaces
Using config file: migration/.tfm.hcl
Getting list of workspaces from:  terraform.local.company
Found 100 Workspaces
Error With retrieving Workspaces from  terraform.local.company  : Error  Trying to Unmarshal an object of type "data-retention-policy-delete-olders", but "data-retention-policies" does not match
```

**Expected behavior**
In the past, it would return a list of all the workspaces counting by groups of 100

**Desktop :**
 - OS: Rhel 8
 - Version 0.9.1

**Comment by Josh-Tracy** [comment]
I suspect this is related to the latest changes made to the TFE API in the latest release. Looking at the go-tfe sdk here https://github.com/hashicorp/go-tfe/releases updating the package used by tfm to 1.48 should resolve this. 

Let me check on backward compatibility first.

**Comment by Josh-Tracy** [comment]
@gaelik release 0.9.2 should resolve this
